# Generated by Django 3.0.8 on 2020-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
