# Generated by Django 3.0.8 on 2020-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('PARAGRAPH', 'Paragraph'), ('SUBTITLE', 'Subtitle'), ('IMG', 'Image')], max_length=200, null=True),
        ),
    ]
