# Generated by Django 3.0.8 on 2020-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('PARAGRAPH', 'Paragraph'), ('SUBTITLE', 'Subtitle'), ('IMG', 'Image'), ('BLOCKQUOTE', 'Blockquote')], max_length=200, null=True),
        ),
    ]
