# Generated by Django 3.0.8 on 2020-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200811_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('PARAGRAPH', 'Paragraph'), ('SUBTITLE', 'Subtitle'), ('IMAGE', 'Image'), ('BLOCKQUOTE', 'Blockquote'), ('CAPTION-TEXT', 'Caption Text')], default='PARAGRAPH', max_length=200),
        ),
    ]
