# Generated by Django 3.0.8 on 2020-08-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200811_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_title',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
