# Generated by Django 3.0.8 on 2020-08-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_slug_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language_code',
            field=models.CharField(default='de-DE', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('PARAGRAPH', 'Paragraph'), ('SUBTITLE', 'Subtitle'), ('IMAGE', 'Image'), ('BLOCKQUOTE', 'Blockquote'), ('CODE', 'Code')], default='PARAGRAPH', max_length=200),
        ),
    ]
