# Generated by Django 3.0.8 on 2020-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200821_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
