# Generated by Django 3.0.8 on 2020-08-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_languagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.LanguageGroup'),
        ),
    ]
