# Generated by Django 3.0.8 on 2020-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_language_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_title',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
