# Generated by Django 3.0.8 on 2020-09-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200823_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('sequence',)},
        ),
    ]
