# Generated by Django 3.0.8 on 2020-08-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0008_auto_20200811_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.Content')),
            ],
        ),
    ]
